apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: greeter-pipeline
  labels:
    app: greeter
spec:
  params: 
    - name: git-url
      description: Git URL Address
      type: string
      default: https://github.com/ppintogbm/liberty-greeter-sample.git
    - name: git-revision
      description: Git Revision to Checkout
      type: string
      default: master
    - name: gitops-url
      description: GitOps URL Address
      type: string
      default: https://github.com/ppintogbm/gitops-samples.git
    - name: gitops-revision
      description: GitOps Revision to Checkout
      type: string
      default: master
    - name: gitops-context
      description: GitOps Context Path
      type: string
      default: greeter
  workspaces:
    - name: source
    - name: gitops
    - name: settings
  tasks:
    - name: fetch-source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
    - name: fetch-gitops
      params:
        - name: url
          value: $(params.gitops-url)
        - name: revision
          value: $(params.gitops-revision)
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: gitops
    - name: build-source
      runAfter:  
        - fetch-source
      taskRef:
        name: maven
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: settings
    - name: get-image-repo 
      params:
        - name: ARGS
          value: 
            - get imagestream greeter --output=jsonpath='{.status.dockerImageRepository}'
      taskRef:
        name: openshift-client-with-output
    - name: build-image
      params:
        - name: IMAGE
          value: $(tasks.get-image-repo.results.output)
      runAfter:
        - build-source
        - get-image-repo
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source
    - name: update-gitops-repo
      params:
        - name: GIT_USER_NAME
          value: Tekton
        - name: GIT_USER_EMAIL
          value: Tekton@openshift.local
        - name: CONTEXT_PATH
          value: greeter
        - name: CONTENT
          value: | 
            ## Update to add image
            images:
              - name: greeter
                newName: $(tasks.get-image-repo.results.output)
                digest: $(tasks.build-image.results.IMAGE_DIGEST)
      runAfter:
        - build-image
        - fetch-gitops
      taskRef:
        name: update-kustomization
      workspaces:
        - name: source
          workspace: gitops