apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: openshift client
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: cli
  name: client-with-workspace
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: redhat
spec:
  workspaces:
    - name: source
      description: Location for manifests
  results:
    - name: resources
      description: Save the list of resources created
  description: >-
    This task runs commands against the cluster where the task run is being
    executed.

    OpenShift is a Kubernetes distribution from Red Hat which provides oc, the
    OpenShift CLI that complements kubectl for simplifying deployment and
    configuration applications on OpenShift.
  params:
    - default: oc $@ --output=json | tee $(results.resources.path)
      description: The OpenShift CLI arguments to run
      name: SCRIPT
      type: string
    - default:
        - help
      description: The OpenShift CLI arguments to run
      name: ARGS
      type: array
  resources:
    inputs:
      - name: source
        optional: true
        type: git
  steps:
    - args:
        - $(params.ARGS)
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
      name: oc
      resources: {}
      script: $(params.SCRIPT) 
